import type {NextPage} from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import {useEffect, useState} from "react";

const Home: NextPage = () => {
    return (<div className={styles.container}>
                <Head>
                    <title>RaceAssist-web</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.png"/>
                </Head>
                <Navbar/>
                <RaceBoard/>
                <PlaceBoard/>
                <HorseBoard/>
                <ResultBoard/>
                <ArticleBoard/>
                <Footer/>
            </div>);
};


// component
function RaceBoard() {
    const [raceList, setRaceList] = useState<string []>([])
    useEffect(() => {
        const setList = async (setData: (arg0: string[]) => void) => {
            const response = await fetch("/server-api/place/list", {
                mode: 'cors'
            })
            const res: RaceList = await response.json()
            setData(res.data.list);
        }

        setList(setRaceList).then(r => r)
    } , [])
    return (<div>
        {
            raceList.map((race) => {
            return <div key={race}>{race}</div>
        })
        }
    </div>)
}

function PlaceBoard() {
    return (<div></div>)
}

function HorseBoard() {
    return (<div></div>)
}

function ResultBoard() {
    return (<div></div>)
}

function ArticleBoard() {
    return (<div></div>)
}

// type interface
interface RaceList {
    data: {
        list: string[]
    }
}

// extend function
// function
// recoil
// selector
// style
// ssr ssg isr
// global function

export default Home;
