import { NextPage } from "next";
import styles from "../../styles/Home.module.css";
import Head from "next/head";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import useSWR from "swr";


const Home: NextPage = () => {
    return (<div className={styles.container}>
        <Head>
            <title>RaceAssist-web</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.png" />
        </Head>
        <Navbar />
        <PlaceCard />
        <Footer />
    </div>);
};


// component
function PlaceCard() {
    const { data, error } = useSWR<PlaceList>(`/server-api/place/list`, fetcher);
    if (error) return <div>failed to load</div>;
    if (!data) return <div>loading...</div>;
    return (<div>
        {data.data.list.map((place) => {
            return <div key={place}>{place}</div>;
        })}
    </div>);
}
// type interface
// extend function
// function
const fetcher = (url: string): Promise<any> => fetch(url).then(res => res.json());
// recoil
// selector
// style
// ssr ssg isr 
// global function
export default Home;